---
- name: Install k3s server
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --tls-san {{ public_ip }}" sh -
  args:
    creates: /usr/local/bin/k3s
  become: yes

- name: Read k3s node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  become: yes
  register: node_token

- name: Save k3s token as fact
  set_fact:
    k3s_token: "{{ node_token.content | b64decode | trim }}"

- name: Fetch kubeconfig
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ./kubeconfig
    flat: yes
  become: yes
